-- AlterTable
ALTER TABLE "patient_actor" ADD COLUMN     "additionalSymptoms" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "avoidMedicalJargon" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "chiefComplaint" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "customInstructions" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "demographics" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "medicalHistory" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "medications" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "personality" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "physicalFindings" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "provideFeedback" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "revelationLevel" TEXT NOT NULL DEFAULT 'moderate',
ADD COLUMN     "socialHistory" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "stayInCharacter" BOOLEAN NOT NULL DEFAULT true,
ALTER COLUMN "prompt" DROP NOT NULL;
